name: "create-telegram-chat"

on: 
  repository_dispatch:
    types: [create-telegram-chat]

jobs:
  create-telegram-chat:
    name: "Create Telegram Chat"
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      BOT_MODE: ${{ secrets.BOT_MODE }}
      BOT_ADMINS: ${{ secrets.BOT_ADMINS }}
      BOT_WEBHOOK: ${{ secrets.BOT_WEBHOOK }}
      BOT_WEBHOOK_SECRET: ${{ secrets.BOT_WEBHOOK_SECRET }}

      TELEGRAM_APP_ID: ${{ secrets.TELEGRAM_APP_ID }}
      TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}

      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

      LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
      DEBUG: ${{ secrets.DEBUG }}
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SERVER_PORT: ${{ secrets.SERVER_PORT }}

    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"

      - name: install dependencies
        run: yarn

      - name: execute directive
        run: npx tsx ./src/workflows/create-chat/index.ts
        id: create-telegram-chat
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          BOT_MODE: ${{ secrets.BOT_MODE }}
          BOT_ADMINS: ${{ secrets.BOT_ADMINS }}
          BOT_WEBHOOK: ${{ secrets.BOT_WEBHOOK }}
          BOT_WEBHOOK_SECRET: ${{ secrets.BOT_WEBHOOK_SECRET }}

          TELEGRAM_APP_ID: ${{ secrets.TELEGRAM_APP_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          
          LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
          DEBUG: ${{ secrets.DEBUG }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}